backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img
display_url: 'https://cyclopolis.fr'
logo_url: 'https://cyclopolis.lavilleavelo.org/Logo_Cyclopolis_v2.png'

collections:
  - name: 'news'
    label: 'Historique'
    description: 'Changelog public de cyclopolis'
    folder: 'content/news'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}'
    editor:
      preview: false
    fields:
      - { label: 'Date', hint: 'Date de la news (affichée à gauche dans la frise)', name: 'date', widget: 'datetime' }
      - { label: 'Texte bannière', hint: "Le texte de la dernière news est affiché dans la bannière d'info en haut de toutes les pages.", name: 'newsBannerText' }
      - { label: 'Contenu', name: 'body', widget: 'markdown' }

  - name: 'compteurs'
    label: 'Compteurs'
    description: 'Compteurs de vélos'
    folder: 'content/compteurs'
    format: 'json'
    extension: 'json'
    create: true
    slug: '{{name}}'
    editor:
      preview: false
    fields:
      - { label: 'Nom', name: 'name', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Arrondissement', name: 'arrondissement', widget: 'string' }
      - { label: "URL de l'image", name: 'imageUrl', widget: 'string' }
      - { label: "identifiant du compteur", name: 'idPdc', widget: 'number' }
      - {
          label: "Coordonnées GPS",
          name: 'coordinates',
          widget: 'code',
      }
      - {
          label: "Relevé des compteurs",
          name: 'counts',
          widget: 'list',
          fields: [
            { label: 'Mois', name: 'month', widget: 'datetime' },
            { label: 'relevé du compteur', name: 'count', widget: 'number' }
          ]
        }




