backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img
display_url: 'https://cyclopolis.fr'
logo_url: 'https://cyclopolis.lavilleavelo.org/Logo_Cyclopolis_v2.png'

collections:
  - name: 'news'
    label: 'Historique'
    description: 'Changelog public de cyclopolis'
    folder: 'content/news'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}'
    editor:
      preview: false
    fields:
      - { label: 'Date', hint: 'Date de la news (affichée à gauche dans la frise)', name: 'date', widget: 'datetime' }
      - { label: 'Texte bannière', hint: "Le texte de la dernière news est affiché dans la bannière d'info en haut de toutes les pages.", name: 'newsBannerText' }
      - { label: 'Contenu', name: 'body', widget: 'markdown' }

  - name: 'blog'
    label: 'Blog'
    description: 'Blog de cyclopolis'
    folder: 'content/blog'
    format: 'frontmatter'
    create: true
    slug: '{{title}}'
    editor:
      preview: false
    fields:
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Image', name: 'imageUrl', widget: 'string' }
      - { label: 'Contenu', name: 'body', widget: 'markdown' }

  - name: 'voies-lyonnaises'
    label: 'Voies Lyonnaises'
    description: 'Liste des Voies Lyonnaises'
    folder: 'content/voies-lyonnaises'
    filter:
      - extension: 'md'
    format: 'frontmatter'
    create: false
    slug: 'ligne-{{line}}'
    editor:
      preview: false
    fields:
      - { label: 'Ligne', name: 'line', widget: 'hidden' }
      - { label: 'Couleur', name: 'color', widget: 'hidden' }
      - { label: 'Depuis', name: 'from', widget: 'string' }
      - { label: 'Destination', name: 'to', widget: 'string' }
      - { label: 'Distance', name: 'distance', widget: 'number' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Trafic', name: 'trafic', widget: 'string' }
      - { label: 'Photo de couverture', name: 'cover', widget: 'string' }
      - { label: 'Contenu', name: 'body', widget: 'markdown' }




